spring.application.name=skynet

# Cloud Database Configuration (Filled by Render Environment Variables)
spring.datasource.url=jdbc:postgresql://skynet_db_6n4q_user:PYpsVqsV8N2N65KJIh9AGqQYbAALpZ6C@dpg-d6n5li4r85hc73de3p30-a/skynet_db_6n4q
spring.datasource.username=skynet_db_6n4q_user
spring.datasource.password=PYpsVqsV8N2N65KJIh9AGqQYbAALpZ6C

# Hibernate Properties for PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

